version: "3.8"
services:
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    command: node index.js

  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 80:3000
    command: npm start
